
name: Lint Helm Chart

on:
  pull_request:
    branches: [ main, master ]

jobs:
  lint-chart:
    runs-on: ubuntu-latest
    env:
      CHART_PATH: localhost:5000
    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Lint chart
        run: |
          helm version
          helm lint "$CHART_PATH"
