name: Trigger update

on:
  push:
    branches:
    - release-*
    paths:
    - 'hello-go/**'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  notify-repo:
    runs-on: ubuntu-latest
    steps:
      # Sends a dispatch event to repo-of-charts to trigger an update
      - name: Notify Repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: JakobGray/repo-of-charts
          event-type: chart-change
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
          